[window]
opacity = 0.94
decorations = "None"

[window.padding]
x = 5
y = 5

[window.class]
general = "Alacritty"
instance = "Alacritty"

[colors.primary]
background = "#101010"
foreground = "#cfcfcf"

[font]
size = 17.0

[font.normal]
family = "Iosevka"
style = "Medium"

[font.bold]
family = "Iosevka"
style = "Bold"

[font.italic]
family = "Iosevka"
style = "Italic"

[[keyboard.bindings]]
key = "Return"
mods = "Alt"
action = "SpawnNewInstance"

